<?php

namespace Tests\Domain\Book\ValueObject;

use App\Domain\Book\Exception\SameDescryptionException;
use App\Domain\Book\ValueObject\Description;
use Tests\TestCase;

class DescriptionTest extends TestCase
{
    /**
     * @var Description
     */
    protected $description;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->description = Description::fromString('test');
    }

    function test_it_to_string()
    {
        $this->assertSame($this->description->toString(), 'test');
    }

    function test_it_change_description()
    {
        $this->description->changeDescription('test2');
        $this->assertSame($this->description->toString(), 'test2');
    }

    function test_it_change_same_description()
    {
        $this->expectException(SameDescryptionException::class);
        $this->description->changeDescription('test');
    }
}