<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Application\Command\Category\Create\CreateCategoryHandler' shared autowired service.

return $this->services['App\Application\Command\Category\Create\CreateCategoryHandler'] = new \App\Application\Command\Category\Create\CreateCategoryHandler();
