<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Common\CommandHandler\CommandBusAbstract' shared autowired service.

return $this->services['App\Infrastructure\Common\CommandHandler\CommandBusAbstract'] = new \App\Infrastructure\Common\CommandHandler\CommandBusAbstract();
