<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ZzLgH5\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ZzLgH5/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7ZzLgH5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container7ZzLgH5\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container7ZzLgH5\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '7ZzLgH5',
    'container.build_id' => '3160eca6',
    'container.build_time' => 1552828477,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ZzLgH5');
