<?php

declare(strict_types=1);

namespace App\Unit;

use App\Kernel;
use Symfony\Component\DependencyInjection\Container;

class TestCase extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Container|null
     */
    protected $container;

    /**
     * @var Kernel
     */
    private $kernel;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->kernel = new Kernel('test', true);
        $this->kernel->boot();
        $this->container = $this->kernel->getContainer();
    }
}
